---
# tasks file for cpu-microcode
- name: Cpu-microcode
  when: ansible_architecture == "x86_64"
  block:
    - name: Get CPU vendor
      ansible.builtin.set_fact:
        cpu_vendor: 'intel'
      when: ansible_processor | lower is search("intel")
      tags:
        - microcode
        - vendor

    - name: Get CPU vendor
      ansible.builtin.set_fact:
        cpu_vendor: 'amd'
      when: ansible_processor | lower is search("amd")
      tags:
        - microcode
        - vendor

    - name: Add related package(s)
      ansible.builtin.package:
        name: "{{ intel_cpu_packages }}"
      when:
        - ansible_virtualization_role == 'host'
        - cpu_vendor == 'intel'
      tags:
        - microcode
        - package
        - add

    - name: Add related package(s)
      ansible.builtin.package:
        name: "{{ amd_cpu_packages }}"
      when:
        - ansible_virtualization_role == 'host'
        - cpu_vendor == 'amd'
      tags:
        - microcode
        - package
        - add

    - name: Remove non related package
      ansible.builtin.package:
        name: "{{ intel_cpu_packages }}"
        state: absent
        purge: true
      when: cpu_vendor == 'amd' or ansible_virtualization_role == 'guest'
      tags:
        - microcode
        - package
        - del

    - name: Remove non related package
      ansible.builtin.package:
        name: "{{ amd_cpu_packages }}"
        state: absent
        purge: true
      when: cpu_vendor == 'intel' or ansible_virtualization_role == 'guest'
      tags:
        - microcode
        - package
        - del
